-- Catálogo sectores Isla de Margarita (Nueva Esparta)
-- Fuente: municipios=FeatureServer ArcGIS DPT002 (códigos INE); sectores=OpenStreetMap (Overpass, ODbL).
-- Generado automáticamente. Revisar nombres antes de producción.

insert into public.municipalities (name, state) values
  ('Antolín del Campo', 'Nueva Esparta'),
  ('Arismendi', 'Nueva Esparta'),
  ('Díaz', 'Nueva Esparta'),
  ('García', 'Nueva Esparta'),
  ('Gómez', 'Nueva Esparta'),
  ('Maneiro', 'Nueva Esparta'),
  ('Marcano', 'Nueva Esparta'),
  ('Mariño', 'Nueva Esparta'),
  ('Península de Macanao', 'Nueva Esparta'),
  ('Tubores', 'Nueva Esparta'),
  ('Villalba', 'Nueva Esparta')
on conflict do nothing;

insert into public.sectors (municipality_id, name)
select m.id, s.name
from public.municipalities m
join (values
  ('Antolín del Campo', 'Aricagua'),
  ('Antolín del Campo', 'Casco Central'),
  ('Antolín del Campo', 'Cimarrón'),
  ('Antolín del Campo', 'El Barrero'),
  ('Antolín del Campo', 'El Cardón'),
  ('Antolín del Campo', 'El Portachuelo'),
  ('Antolín del Campo', 'El Rincón'),
  ('Antolín del Campo', 'El Salado'),
  ('Antolín del Campo', 'El Tirano'),
  ('Antolín del Campo', 'El Toco'),
  ('Antolín del Campo', 'Guarame'),
  ('Antolín del Campo', 'Güirigüire'),
  ('Antolín del Campo', 'La Estancia'),
  ('Antolín del Campo', 'La Fuente'),
  ('Antolín del Campo', 'La Mira'),
  ('Antolín del Campo', 'La Plaza Paraguachí'),
  ('Antolín del Campo', 'La Polvorosa'),
  ('Antolín del Campo', 'La Rinconada'),
  ('Antolín del Campo', 'La Rumencito'),
  ('Antolín del Campo', 'La Sabana'),
  ('Antolín del Campo', 'Las Flandes'),
  ('Antolín del Campo', 'Los Colorados'),
  ('Antolín del Campo', 'Los Ranchos de Chana'),
  ('Antolín del Campo', 'Manzanillo'),
  ('Antolín del Campo', 'Pachaco'),
  ('Antolín del Campo', 'Playa Cardón'),
  ('Antolín del Campo', 'Playa El Agua'),
  ('Antolín del Campo', 'Playa Manzanillo'),
  ('Antolín del Campo', 'Playa Parguito'),
  ('Antolín del Campo', 'Pozo de Agua'),
  ('Antolín del Campo', 'Urbanización Sabana de El Tirano'),
  ('Antolín del Campo', 'Viento Fresco'),
  ('Arismendi', 'Atamo Norte'),
  ('Arismendi', 'Atamo Sur'),
  ('Arismendi', 'Brisas de La Asunción'),
  ('Arismendi', 'Camoruco'),
  ('Arismendi', 'Cantarrana'),
  ('Arismendi', 'Casco Histórico'),
  ('Arismendi', 'Cocheima'),
  ('Arismendi', 'El Chorro'),
  ('Arismendi', 'El Conchal'),
  ('Arismendi', 'El Copey'),
  ('Arismendi', 'El Limón'),
  ('Arismendi', 'El Mamey'),
  ('Arismendi', 'El Samán'),
  ('Arismendi', 'El Tamarindo'),
  ('Arismendi', 'Guatamare'),
  ('Arismendi', 'Guayabal La Caña'),
  ('Arismendi', 'La Aguada'),
  ('Arismendi', 'La Portada'),
  ('Arismendi', 'La Sierra'),
  ('Arismendi', 'Los Chuares'),
  ('Arismendi', 'Palo Sano'),
  ('Arismendi', 'Quebrancho de Arismendi'),
  ('Arismendi', 'Sabana de Guacuco'),
  ('Arismendi', 'Salamanca'),
  ('Arismendi', 'San Martín de Porres'),
  ('Arismendi', 'Santa Isabel de Hungría'),
  ('Arismendi', 'Urbanización Guanare'),
  ('Díaz', 'Agua de Vaca'),
  ('Díaz', 'Boquerón'),
  ('Díaz', 'Carapacho'),
  ('Díaz', 'Casco Central'),
  ('Díaz', 'Cotoperíz'),
  ('Díaz', 'El Dátil'),
  ('Díaz', 'El Espinal'),
  ('Díaz', 'El Hatico'),
  ('Díaz', 'El Macho'),
  ('Díaz', 'El Manglillo'),
  ('Díaz', 'El Rincón'),
  ('Díaz', 'El Tuey'),
  ('Díaz', 'El Yaque'),
  ('Díaz', 'Fuentidueño'),
  ('Díaz', 'Guatacaral'),
  ('Díaz', 'La Cruz del Pastel'),
  ('Díaz', 'La Guardia'),
  ('Díaz', 'La Salineta'),
  ('Díaz', 'Las Barrancas'),
  ('Díaz', 'Las Bermúdez'),
  ('Díaz', 'Las Guevaras'),
  ('Díaz', 'Lomas de El Yaque'),
  ('Díaz', 'Los Bagres'),
  ('Díaz', 'Los Fermines'),
  ('Díaz', 'Los Villaroel'),
  ('Díaz', 'Piedras Negras'),
  ('Díaz', 'Punta Cuji'),
  ('Díaz', 'Punta Sabita'),
  ('Díaz', 'Sector El Copey'),
  ('Díaz', 'Urbanización Brisas del Caraney'),
  ('Díaz', 'Urbanización Cerromar'),
  ('Díaz', 'Urbanización Chaguaramal'),
  ('Díaz', 'Urbanización Cotoperíz I'),
  ('Díaz', 'Urbanización Cotoperíz II'),
  ('Díaz', 'Urbanización El Morichal'),
  ('Díaz', 'Urbanización La Guarida del Sol'),
  ('Díaz', 'Urbanización La Pista'),
  ('Díaz', 'Valle Verde'),
  ('García', 'Barrio El Guayabo'),
  ('García', 'Bloques de Villa Rosa'),
  ('García', 'Conejeros'),
  ('García', 'Conuco Viejo'),
  ('García', 'Doña Elisa'),
  ('García', 'El Hato'),
  ('García', 'El Toporo'),
  ('García', 'El Valle del Espíritu Santo'),
  ('García', 'Guatamare'),
  ('García', 'La Isleta'),
  ('García', 'Las Piedras'),
  ('García', 'Praderas de San Antonio'),
  ('García', 'San Antonio'),
  ('García', 'Urbanización 28 de Mayo'),
  ('García', 'Urbanización Marisal'),
  ('García', 'Urbanización Nueva Esparta'),
  ('García', 'Urbanización Pedro Luis Briceño'),
  ('García', 'Urbanización Villa Juana'),
  ('García', 'Urbanización Villa Rosa'),
  ('García', 'Urbanización Villas de San Antonio'),
  ('Gómez', 'Altagracia'),
  ('Gómez', 'Bahía de Plata'),
  ('Gómez', 'Belén'),
  ('Gómez', 'Blanco Lugar'),
  ('Gómez', 'Conjunto Residencial NENA II'),
  ('Gómez', 'El Cercado'),
  ('Gómez', 'El Maco'),
  ('Gómez', 'El Salado'),
  ('Gómez', 'Guayacán'),
  ('Gómez', 'La Boquita'),
  ('Gómez', 'La Tagua'),
  ('Gómez', 'La Vecindad'),
  ('Gómez', 'Las Gamboas'),
  ('Gómez', 'Pedro González'),
  ('Gómez', 'Residencias Catame'),
  ('Gómez', 'Residencias Villas Castilla Mar'),
  ('Gómez', 'San Sebastián'),
  ('Gómez', 'Santa Ana'),
  ('Gómez', 'Tacarigua'),
  ('Gómez', 'Urbanización La Isla'),
  ('Gómez', 'Urbanización Los Cocoteros'),
  ('Gómez', 'Urbanización Los Veleros'),
  ('Gómez', 'Urbanización Nuevo Juan Griego'),
  ('Gómez', 'Villa Castillamar'),
  ('Maneiro', '1°. Etapa de Jorge Coll'),
  ('Maneiro', '2°. Etapa de Jorge Coll'),
  ('Maneiro', 'Agua de Vaca'),
  ('Maneiro', 'Apostadero'),
  ('Maneiro', 'Barrio Los Pescadores'),
  ('Maneiro', 'Campiare'),
  ('Maneiro', 'Casco Central'),
  ('Maneiro', 'El Hato'),
  ('Maneiro', 'El Potrero'),
  ('Maneiro', 'La Caranta'),
  ('Maneiro', 'Las Casitas'),
  ('Maneiro', 'Los Cerritos'),
  ('Maneiro', 'Los Chacos'),
  ('Maneiro', 'Los Pozos'),
  ('Maneiro', 'Los Robles'),
  ('Maneiro', 'Micaure'),
  ('Maneiro', 'Playa Moreno'),
  ('Maneiro', 'Polanco'),
  ('Maneiro', 'San Lorenzo'),
  ('Maneiro', 'Urbanización Fundación Margarita'),
  ('Maneiro', 'Urbanización Jorge Coll'),
  ('Maneiro', 'Urbanización Jóvilo Villalba'),
  ('Maneiro', 'Urbanización Maneiro'),
  ('Maneiro', 'Urbanización Nuevo Mundo'),
  ('Maneiro', 'Urbanización Paraíso'),
  ('Maneiro', 'Urbanización Playa El Ángel'),
  ('Maneiro', 'Urbanización San Fernando'),
  ('Marcano', 'Boca de Monte'),
  ('Marcano', 'Casco Central'),
  ('Marcano', 'El Morro'),
  ('Marcano', 'El Tamarindo'),
  ('Marcano', 'La Cruz'),
  ('Marcano', 'La Galera'),
  ('Marcano', 'Las Cabreras'),
  ('Marcano', 'Los Millanes'),
  ('Marcano', 'Pedregales'),
  ('Marcano', 'Urbanización Alberto Lobera'),
  ('Marcano', 'Urbanización Francisco Adrián'),
  ('Marcano', 'Valparaíso'),
  ('Marcano', 'Vizcuña'),
  ('Mariño', 'Achipano'),
  ('Mariño', 'Aeropuerto Viejo'),
  ('Mariño', 'Barrio Brasil'),
  ('Mariño', 'Barrio Colindante'),
  ('Mariño', 'Barrio El Clavelito'),
  ('Mariño', 'Bella Vista'),
  ('Mariño', 'Brisas de Achipano'),
  ('Mariño', 'Campomar'),
  ('Mariño', 'Centro'),
  ('Mariño', 'Cerro Colorado'),
  ('Mariño', 'Ciudad Cartón'),
  ('Mariño', 'Cruz Grande'),
  ('Mariño', 'El Cuarto'),
  ('Mariño', 'El Piache'),
  ('Mariño', 'El Poblado'),
  ('Mariño', 'El Silguero'),
  ('Mariño', 'Fajardo'),
  ('Mariño', 'Genovés'),
  ('Mariño', 'Llano Adentro'),
  ('Mariño', 'Los Cocos'),
  ('Mariño', 'Los Cocos Norte'),
  ('Mariño', 'Los Delfines'),
  ('Mariño', 'Macho Muerto'),
  ('Mariño', 'Morro El Palmar'),
  ('Mariño', 'Palguarime'),
  ('Mariño', 'Pueblo Nuevo'),
  ('Mariño', 'Punda'),
  ('Mariño', 'Sector Cocopozuelo'),
  ('Mariño', 'Urbanismo Luisa Cáceres de Arismendi'),
  ('Mariño', 'Urbanización Ali Primera'),
  ('Mariño', 'Urbanización Costa Azul'),
  ('Mariño', 'Urbanización Dumar Country Club'),
  ('Mariño', 'Urbanización La Arboleda'),
  ('Mariño', 'Urbanización Los Restos'),
  ('Mariño', 'Urbanización Sabanamar'),
  ('Mariño', 'Urbanización Táchira'),
  ('Mariño', 'Villas de Campo'),
  ('Mariño', 'Vista Bella I'),
  ('Mariño', 'Vista Bella II'),
  ('Mariño', 'Vista Bella III'),
  ('Mariño', 'Vista Bella IV'),
  ('Mariño', 'Zona Industrial de El Piache'),
  ('Península de Macanao', 'Arenas'),
  ('Península de Macanao', 'Arenitas'),
  ('Península de Macanao', 'Barbasco'),
  ('Península de Macanao', 'Barrancas'),
  ('Península de Macanao', 'Barrio Caracas'),
  ('Península de Macanao', 'Boca del Pozo'),
  ('Península de Macanao', 'Boca del Río'),
  ('Península de Macanao', 'Campo Arriba'),
  ('Península de Macanao', 'Caraquita'),
  ('Península de Macanao', 'Chacaracual'),
  ('Península de Macanao', 'Champoturo'),
  ('Península de Macanao', 'Comejenes'),
  ('Península de Macanao', 'Crucero de Macanao'),
  ('Península de Macanao', 'Curichicual'),
  ('Península de Macanao', 'El Campo'),
  ('Península de Macanao', 'El Carujo'),
  ('Península de Macanao', 'El Cascabel'),
  ('Península de Macanao', 'El Cementerio'),
  ('Península de Macanao', 'El Horcón'),
  ('Península de Macanao', 'El Indio'),
  ('Península de Macanao', 'El Manantial'),
  ('Península de Macanao', 'El Manglillo'),
  ('Península de Macanao', 'El Pozo'),
  ('Península de Macanao', 'El Relámpago'),
  ('Península de Macanao', 'El Robledal'),
  ('Península de Macanao', 'El Tunal'),
  ('Península de Macanao', 'Guamachito'),
  ('Península de Macanao', 'Guayacancito'),
  ('Península de Macanao', 'La Auyama'),
  ('Península de Macanao', 'La Escusa'),
  ('Península de Macanao', 'La Figa'),
  ('Península de Macanao', 'La Paliza'),
  ('Península de Macanao', 'La Pared'),
  ('Península de Macanao', 'La Salina'),
  ('Península de Macanao', 'La Yegua'),
  ('Península de Macanao', 'Las Lajas'),
  ('Península de Macanao', 'Las Vegas'),
  ('Península de Macanao', 'Los Robles'),
  ('Península de Macanao', 'Manzanillito'),
  ('Península de Macanao', 'Navio Quebrao'),
  ('Península de Macanao', 'Pedro Luis Briceño'),
  ('Península de Macanao', 'Playa Brava'),
  ('Península de Macanao', 'Punta Arenas'),
  ('Península de Macanao', 'Punta Manzanillo'),
  ('Península de Macanao', 'Párate Bueno'),
  ('Península de Macanao', 'Raúl Leoni'),
  ('Península de Macanao', 'San Francisco de Macanao'),
  ('Península de Macanao', 'Santa Inés'),
  ('Península de Macanao', 'Sector 1 de El Manantial'),
  ('Península de Macanao', 'Sector 2 de El Manantial'),
  ('Península de Macanao', 'Sector Buenos Aires'),
  ('Península de Macanao', 'Sector Los Marinos'),
  ('Península de Macanao', 'Urbanización Augusto Malavé Villalba'),
  ('Tubores', 'Barrio Las Mercedes'),
  ('Tubores', 'Barrio Simón Marval'),
  ('Tubores', 'Boca de Palo'),
  ('Tubores', 'Chacachacare'),
  ('Tubores', 'El Guamache'),
  ('Tubores', 'El Indio'),
  ('Tubores', 'El Sur'),
  ('Tubores', 'El Águila'),
  ('Tubores', 'La Blanquilla'),
  ('Tubores', 'La Giles'),
  ('Tubores', 'La Ponderosa'),
  ('Tubores', 'La Restinga'),
  ('Tubores', 'Laguna de Raya'),
  ('Tubores', 'Las Cuibas'),
  ('Tubores', 'Las Hernández'),
  ('Tubores', 'Las Lares'),
  ('Tubores', 'Las Mariales'),
  ('Tubores', 'Las Marvales'),
  ('Tubores', 'Las Vásquez'),
  ('Tubores', 'Los Algodones'),
  ('Tubores', 'Los Gómez'),
  ('Tubores', 'Los Narvales'),
  ('Tubores', 'Mata Redonda'),
  ('Tubores', 'Orinoco'),
  ('Tubores', 'Palo Sano'),
  ('Tubores', 'Punta de Mangle'),
  ('Tubores', 'Punta de Piedras'),
  ('Tubores', 'Santa María'),
  ('Tubores', 'Urbanización El Aguila'),
  ('Tubores', 'Urbanización Las Mercedes'),
  ('Tubores', 'Urbanización Perlas de Cubagua')
) as s(mun, name) on s.mun = m.name and m.state = 'Nueva Esparta'
on conflict do nothing;
